name: auto publish to my blog
on:
  push:
    branches: [ version ]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@version
      # 安装hugo
    - name: setup hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true
    - name: Build
      run: hugo -D
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        external_repository: nio755/nio755.github.io
        publish_dir: ./public
        publish_branch: master
        enable_jekyll: true
        allow_empty_commit: true
